"use client";

import { ChangeEvent, DragEvent, FormEvent, KeyboardEvent, useEffect, useRef, useState } from "react";
import { Activity, ArrowUp, ArrowUpRight, BookOpen, Check, ChevronRight, Clipboard, FileText, HelpCircle, Home as HomeIcon, Image as ImageIcon, Menu, Mic, Paperclip, Plus, RefreshCw, Settings, ShieldCheck, Sparkles, Stethoscope, Trash2, UserRound, Volume2, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { PremiumLanding } from "./premium-landing";

type Source = { number: number; title: string; publisher: string; published?: string; reviewed?: string; url?: string };
type Message = { role: "user" | "assistant"; content: string };
type HealthStatus = { status: string; detail: string };
type HealthResponse = { status: string; ready: number; total: number; statuses: Record<string, HealthStatus> };
type View = "conversation" | "documents" | "visit" | "sources";

const API_URL = process.env.NEXT_PUBLIC_API_URL || (process.env.NODE_ENV === "development" ? "http://localhost:8000" : "");
const API_CONFIGURATION_MESSAGE = "The deployed frontend has no AI service URL. Set NEXT_PUBLIC_API_URL to the HTTPS address of the FastAPI backend and redeploy.";
const quickActions = [
  ["Ask a health question", "Get a clear, evidence-supported explanation.", BookOpen, "What would you like to understand about your health?"],
  ["Understand a document", "Review visible information before you reason from it.", FileText, "Help me understand this health document in plain language."],
  ["Prepare for a visit", "Organize what you want to ask a clinician.", Stethoscope, "Help me prepare questions for my next healthcare visit."],
] as const;
const healthLabels: Record<string, string> = { fastapi: "FastAPI", ollama: "Ollama", text_model: "Text model", vision_model: "Vision model", embedding_model: "Embedding model", vector_store: "Vector store", whisper: "Whisper", piper: "Piper TTS", translation_model: "Translation model" };

export default function Home() {
  const [workspace, setWorkspace] = useState(false);
  const [view, setView] = useState<View>("conversation");
  const [messages, setMessages] = useState<Message[]>([]);
  const [answer, setAnswer] = useState("");
  const [question, setQuestion] = useState("");
  const [sources, setSources] = useState<Source[]>([]);
  const [loadingStage, setLoadingStage] = useState("");
  const [error, setError] = useState("");
  const [health, setHealth] = useState<HealthResponse | null>(null);
  const [healthOpen, setHealthOpen] = useState(false);
  const [privacyOpen, setPrivacyOpen] = useState(false);
  const [selectedSource, setSelectedSource] = useState<number | null>(null);
  const [language, setLanguage] = useState("English");
  const [recording, setRecording] = useState(false);
  const [document, setDocument] = useState<{ name: string; data: Record<string, unknown> } | null>(null);
  const [documentPreviewUrl, setDocumentPreviewUrl] = useState<string | null>(null);
  const [documentDragging, setDocumentDragging] = useState(false);
  const [visitFields, setVisitFields] = useState<Record<string, string>>({});
  const fileInput = useRef<HTMLInputElement>(null);
  const recorder = useRef<MediaRecorder | null>(null);
  const audioChunks = useRef<Blob[]>([]);

  useEffect(() => { if (workspace) void checkHealth(); }, [workspace]);
  useEffect(() => () => { if (documentPreviewUrl) URL.revokeObjectURL(documentPreviewUrl); }, [documentPreviewUrl]);

  async function checkHealth() {
    try { const response = await fetch(`${API_URL}/api/health`); if (!response.ok) throw new Error(); setHealth(await response.json()); }
    catch { setHealth({ status: "unavailable", ready: 0, total: 9, statuses: {} }); }
  }

  async function sendQuestion(event?: FormEvent, preset?: string) {
    event?.preventDefault();
    const text = (preset ?? question).trim();
    if (!text || loadingStage) return;
    setWorkspace(true); setView("conversation"); setQuestion(""); setError(""); setLoadingStage("Checking safety...");
    const nextHistory = [...messages, { role: "user" as const, content: text }];
    setMessages(nextHistory); setAnswer(""); setSources([]);
    try {
      setLoadingStage("Searching trusted sources...");
      const response = await fetch(`${API_URL}/api/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text, history: messages }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || "The local AI service is unavailable.");
      setLoadingStage("Validating citations...");
      setAnswer(data.answer || "No answer was returned."); setSources(data.sources || []); setMessages([...nextHistory, { role: "assistant", content: data.answer || "" }]);
    } catch { setError(API_URL ? "MediGuide could not reach the local AI service." : API_CONFIGURATION_MESSAGE); setMessages(messages); }
    finally { setLoadingStage(""); }
  }

  async function uploadDocument(file: File) {
    setView("documents"); setError(""); setDocumentDragging(false); setDocumentPreviewUrl(file.type.startsWith("image/") ? URL.createObjectURL(file) : null); setLoadingStage("Reading visible information...");
    const form = new FormData(); form.append("file", file);
    try {
      const response = await fetch(`${API_URL}/api/documents/analyze`, { method: "POST", body: form }); const data = await response.json();
      if (!response.ok) throw new Error(data.detail || "Document analysis failed.");
      setDocument({ name: file.name, data: data.data || {} }); setLoadingStage("");
    } catch { setDocumentPreviewUrl(null); setLoadingStage(""); setError(API_URL ? "MediGuide could not read that document. Check the file and try again." : API_CONFIGURATION_MESSAGE); }
  }

  function onDrop(event: DragEvent<HTMLDivElement>) { event.preventDefault(); setDocumentDragging(false); const file = event.dataTransfer.files[0]; if (file) void uploadDocument(file); }
  function onFileChange(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) void uploadDocument(file); }

  async function toggleVoice() {
    if (recording) { recorder.current?.stop(); setRecording(false); setLoadingStage("Creating transcript..."); return; }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const next = new MediaRecorder(stream); audioChunks.current = [];
      next.ondataavailable = (event) => audioChunks.current.push(event.data);
        next.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); const form = new FormData(); form.append("file", new Blob(audioChunks.current, { type: "audio/webm" }), "question.webm"); try { const response = await fetch(`${API_URL}/api/transcribe`, { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(); setQuestion(data.text || ""); } catch { setError("MediGuide could not create a transcript. Your audio was not sent."); } finally { setLoadingStage(""); } };
      recorder.current = next; next.start(); setRecording(true); setLoadingStage("Listening locally...");
    } catch { setError("Microphone access was not available. Your question has not been sent."); }
  }

  function handleComposerKey(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void sendQuestion(); } }
  function clearSession() { setMessages([]); setAnswer(""); setQuestion(""); setSources([]); setDocument(null); setDocumentPreviewUrl(null); setError(""); setView("conversation"); }
  function retry() { const last = [...messages].reverse().find((item) => item.role === "user"); if (last) void sendQuestion(undefined, last.content); }
  function copyAnswer() { if (answer) void navigator.clipboard?.writeText(answer); }
  function readAnswer() { if (!answer) return; void fetch(`${API_URL}/api/speak`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: answer.replace(/[#*_\[\]]/g, "") }) }).then(async (response) => { if (!response.ok) throw new Error(); const audio = new Audio(URL.createObjectURL(await response.blob())); await audio.play(); }).catch(() => setError("Spoken output is unavailable right now.")); }
  async function translateAnswer(target: string) { if (!answer) return; setLoadingStage(`Translating to ${target}...`); try { const response = await fetch(`${API_URL}/api/translate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: answer, language: target }) }); const data = await response.json(); if (!response.ok) throw new Error(); setAnswer(data.text || answer); setLanguage(target); } catch { setError("MediGuide could not translate this answer right now."); } finally { setLoadingStage(""); } }
  function generateVisitSummary() { const summary = Object.entries(visitFields).filter(([, value]) => value.trim()).map(([key, value]) => `${key}: ${value}`).join("\n\n"); setQuestion(`Help me prepare questions for a healthcare professional using these patient-provided notes:\n\n${summary}`); setView("conversation"); }

  if (!workspace) return <PremiumLanding onStart={() => setWorkspace(true)} />;
  return <main className="product-shell"><header className="app-header"><button className="app-brand" onClick={() => setWorkspace(false)}><span className="brand-mark"><Sparkles size={15} /></span><span>MediGuide <em>AI</em></span></button><span className="header-context">Your private health education workspace</span><div className="header-actions"><select className="language-select" value={language} onChange={(event) => void translateAnswer(event.target.value)} aria-label="Response language"><option>English</option><option>Spanish</option><option>French</option></select><button className="local-pill" onClick={() => setHealthOpen(true)}><span /> Private local</button><button className="icon-button" title="Help"><HelpCircle size={18} /></button><button className="icon-button" title="Settings"><Settings size={18} /></button><button className="profile-button" title="Profile"><UserRound size={17} /></button></div><button className="mobile-menu icon-button" title="Open navigation"><Menu size={20} /></button></header><div className="workspace-grid"><Sidebar view={view} setView={setView} onNew={clearSession} onPrivacy={() => setPrivacyOpen(true)} /><section className="main-panel">{view === "conversation" && <Conversation answer={answer} sources={sources} question={question} messages={messages} loading={loadingStage} error={error} selectedSource={selectedSource} setSelectedSource={setSelectedSource} onRetry={retry} onPreset={(prompt) => setQuestion(prompt)} onAction={(action) => { if (action === "copy") copyAnswer(); if (action === "listen") readAnswer(); if (action === "simple") void sendQuestion(undefined, `Explain this answer simply:\n\n${answer}`); if (action === "questions") { setQuestion("What questions should I ask my clinician about this?"); } }} />}{view === "documents" && <Documents document={document} previewUrl={documentPreviewUrl} dragging={documentDragging} onUpload={() => fileInput.current?.click()} onDrop={onDrop} onDragEnter={() => setDocumentDragging(true)} onDragLeave={() => setDocumentDragging(false)} loading={loadingStage} error={error} />}{view === "visit" && <Visit fields={visitFields} setFields={setVisitFields} onGenerate={generateVisitSummary} />}{view === "sources" && <Sources sources={sources} onSelect={setSelectedSource} />}{view !== "documents" && view !== "visit" && <Composer question={question} setQuestion={setQuestion} onSubmit={sendQuestion} onKeyDown={handleComposerKey} onUpload={() => fileInput.current?.click()} onVoice={toggleVoice} recording={recording} loading={Boolean(loadingStage)} />}<input ref={fileInput} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,image/*" hidden onChange={onFileChange} /></section><Evidence sources={sources} selected={selectedSource} onSelect={setSelectedSource} /></div>{privacyOpen && <Privacy onClose={() => setPrivacyOpen(false)} onClear={clearSession} />}{healthOpen && <Health health={health} onClose={() => setHealthOpen(false)} onRetry={checkHealth} />}</main>;
}

/* Legacy landing markup retained for reference; PremiumLanding is the public entry point. */

function Sidebar({ view, setView, onNew, onPrivacy }: { view: View; setView: (view: View) => void; onNew: () => void; onPrivacy: () => void }) { const item = (target: View, label: string, Icon: LucideIcon) => <button className={view === target ? "nav-item active" : "nav-item"} onClick={() => setView(target)}><Icon size={17} />{label}</button>; return <aside className="sidebar"><div className="sidebar-label">WORKSPACE</div><button className="new-conversation" onClick={onNew}><Plus size={17} /> New conversation</button><nav>{item("conversation", "Conversations", HomeIcon)}{item("documents", "Documents", FileText)}{item("visit", "Visit preparation", Stethoscope)}</nav><div className="sidebar-label knowledge-label">KNOWLEDGE</div><nav>{item("sources", "Sources", BookOpen)}</nav><div className="sidebar-label system-label">SYSTEM</div><nav><button className="nav-item" onClick={onPrivacy}><ShieldCheck size={17} /> Privacy</button><button className="nav-item"><Settings size={17} /> Settings</button></nav><div className="sidebar-footer"><span className="status-dot" /> <div><strong>Private local mode</strong><small>Session-only storage</small></div></div></aside>; }

function Conversation({ answer, sources, messages, loading, error, selectedSource, setSelectedSource, onRetry, onPreset, onAction }: { answer: string; sources: Source[]; question: string; messages: Message[]; loading: string; error: string; selectedSource: number | null; setSelectedSource: (value: number | null) => void; onRetry: () => void; onPreset: (prompt: string) => void; onAction: (action: "copy" | "listen" | "simple" | "questions") => void }) { const lastQuestion = [...messages].reverse().find((item) => item.role === "user"); return <div className="conversation-view"><div className="conversation-header"><div><p className="eyebrow">PRIVATE • LOCAL • EVIDENCE-SUPPORTED</p><h2>{answer ? "Your health question, clarified." : "What can I help you understand today?"}</h2>{!answer && <p>Ask a health question, review a document, use your voice, or prepare for an appointment.</p>}</div><div className="conversation-meta"><span className="response-count">{messages.filter((message) => message.role === "user").length} session {messages.filter((message) => message.role === "user").length === 1 ? "question" : "questions"}</span><span className="care-mode"><ShieldCheck size={13} /> Educational support</span></div></div>{!answer && !loading && <div className="quick-actions">{quickActions.map(([title, description, Icon, prompt]) => <button key={title} onClick={() => { onPreset(prompt); document.querySelector<HTMLTextAreaElement>(".composer textarea")?.focus(); }}><span className="quick-icon"><Icon size={18} /></span><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={17} /></button>)}</div>}{lastQuestion && <div className="user-question"><span>You asked</span><p>{lastQuestion.content}</p></div>}{error && <div className="service-error"><Activity size={19} /><div><strong>MediGuide couldn’t reach the local AI service.</strong><p>Your question has not been sent.</p></div><button onClick={onRetry}><RefreshCw size={15} /> Retry</button></div>}{loading && <div className="processing"><Sparkles size={17} /><span>{loading}</span><i /><i /><i /></div>}{answer && <Answer answer={answer} sources={sources} selectedSource={selectedSource} setSelectedSource={setSelectedSource} onAction={onAction} />}</div>; }

function Answer({ answer, sources, selectedSource, setSelectedSource, onAction }: { answer: string; sources: Source[]; selectedSource: number | null; setSelectedSource: (value: number | null) => void; onAction: (action: "copy" | "listen" | "simple" | "questions") => void }) { const lines = answer.split("\n"); return <article className="answer-document"><div className="answer-kicker"><span><Sparkles size={14} /> MEDIGUIDE</span><small>Evidence checked</small></div><div className="answer-content">{lines.map((line, index) => { const heading = line.startsWith("#"); const parts = line.split(/(\[\d+\])/g); return <p className={heading ? "answer-heading" : ""} key={index}>{parts.map((part, partIndex) => /^\[\d+\]$/.test(part) ? <button className={selectedSource === Number(part.replace(/\D/g, "")) ? "citation selected" : "citation"} onClick={() => setSelectedSource(Number(part.replace(/\D/g, "")))} key={partIndex}>{part}</button> : part.replace(/^#+\s*/, ""))}</p>; })}</div><div className="response-actions"><button onClick={() => onAction("copy")}><Clipboard size={14} /> Copy</button><button onClick={() => onAction("listen")}><Volume2 size={14} /> Listen</button><button onClick={() => onAction("simple")}><Sparkles size={14} /> Explain simply</button><button onClick={() => onAction("questions")}><Stethoscope size={14} /> Questions for clinician</button><button onClick={() => setSelectedSource(sources.length ? sources[0].number : null)}><BookOpen size={14} /> Show sources</button></div></article>; }

function Composer({ question, setQuestion, onSubmit, onKeyDown, onUpload, onVoice, recording, loading }: { question: string; setQuestion: (value: string) => void; onSubmit: (event?: FormEvent) => void; onKeyDown: (event: KeyboardEvent<HTMLTextAreaElement>) => void; onUpload: () => void; onVoice: () => void; recording: boolean; loading: boolean }) { return <form className="composer" onSubmit={onSubmit} onDragOver={(event) => event.preventDefault()}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={onKeyDown} placeholder="Ask a health question, explain a document, or prepare for a visit..." rows={3} /><div className="composer-footer"><div><button type="button" onClick={onUpload}><Paperclip size={16} /> Attach</button><button type="button" className={recording ? "recording" : ""} onClick={onVoice}><Mic size={16} /> {recording ? "Listening" : "Voice"}</button><span>Enter to send · Shift + Enter for a new line</span></div><button className="send-button" disabled={loading || !question.trim()} aria-label="Send"><ArrowUp size={20} /></button></div></form>; }

function Evidence({ sources, selected, onSelect }: { sources: Source[]; selected: number | null; onSelect: (value: number | null) => void }) { return <aside className="evidence"><div className="evidence-top"><div><p className="eyebrow">EVIDENCE</p><h3>Sources &amp; context</h3></div><button className="icon-button" title="Search sources"><BookOpen size={17} /></button></div>{sources.length ? <><div className="support-level"><span>Evidence support</span><strong>{sources.length > 2 ? "STRONG" : sources.length === 2 ? "MODERATE" : "LIMITED"}</strong></div>{sources.map((source) => <button className={selected === source.number ? "source-card selected" : "source-card"} key={source.number} onClick={() => onSelect(source.number)}><span className="source-number">[{source.number}]</span><span><strong>{source.publisher}</strong><b>{source.title}</b><small>{source.reviewed ? `Reviewed ${source.reviewed}` : "Approved knowledge source"}</small><em>Relevant passage available <ArrowUpRight size={12} /></em></span></button>)}</> : <div className="evidence-empty"><BookOpen size={22} /><strong>Sources &amp; evidence</strong><p>Trusted sources used for your answer will appear here.</p></div>}<div className="evidence-note"><ShieldCheck size={16} /><span>Sources are retrieved from the approved local knowledge base.</span></div></aside>; }

function Documents({ document, previewUrl, dragging, onUpload, onDrop, onDragEnter, onDragLeave, loading, error }: { document: { name: string; data: Record<string, unknown> } | null; previewUrl: string | null; dragging: boolean; onUpload: () => void; onDrop: (event: DragEvent<HTMLDivElement>) => void; onDragEnter: () => void; onDragLeave: () => void; loading: string; error: string }) { return <div className="workflow-view"><div className="workflow-heading-row"><div><p className="eyebrow">DOCUMENT REVIEW</p><h2>Understand the details.</h2><p className="workflow-lead">Review visible information before it becomes part of a question.</p></div><span className="workflow-badge"><ShieldCheck size={14} /> Human review first</span></div>{!document && !loading && <div className={dragging ? "upload-zone is-dragging" : "upload-zone"} onDrop={onDrop} onDragEnter={(event) => { event.preventDefault(); onDragEnter(); }} onDragOver={(event) => event.preventDefault()} onDragLeave={onDragLeave}><span className="upload-art"><FileText size={25} /><span><ImageIcon size={14} /></span></span><strong>Upload a health document</strong><span>Drop an image or PDF here, or choose a file</span><small>PDF, PNG, JPG, WEBP · Temporary session file</small><button className="forest-button" onClick={onUpload}>Choose file <Paperclip size={16} /></button></div>}{loading && <div className="processing large"><Sparkles size={18} /> {loading}<i /><i /><i /></div>}{error && <div className="service-error"><Activity size={19} /><div><strong>{error}</strong><p>Your document has not been added.</p></div></div>}{document && <div className="document-review"><div className="document-meta"><FileText size={18} /><span><strong>{document.name}</strong><small>Ready for review · temporary session file</small></span><Check size={18} /></div><div className="extraction-grid"><div className="document-preview">{previewUrl ? <img src={previewUrl} alt="Uploaded health document preview" /> : <FileText size={38} />}<span>{previewUrl ? "Uploaded image" : "Original document"}</span><small>Check names, values, units, and dates</small></div><div className="extracted-fields"><p className="eyebrow">EXTRACTED INFORMATION</p>{Object.entries(document.data).filter(([key]) => key !== "visible_text" && key !== "uncertain_text").slice(0, 5).map(([key, value]) => <label key={key}>{key.replaceAll("_", " ")}<input value={typeof value === "string" ? value : JSON.stringify(value)} readOnly /></label>)}<div className="review-key"><span>Clearly visible</span><span>Needs review</span><span>Could not read</span></div><label className="confirm"><input type="checkbox" /> I reviewed names, values, units, and dates.</label></div></div></div>}</div>; }

function Visit({ fields, setFields, onGenerate }: { fields: Record<string, string>; setFields: (value: Record<string, string>) => void; onGenerate: () => void }) { const names = ["Main concern", "Symptoms", "Symptom timeline", "Duration", "Severity", "Triggers", "Medications entered by user", "Questions for clinician", "Missing information"]; return <div className="workflow-view"><p className="eyebrow">VISIT PREPARATION</p><h2>Make the visit count.</h2><p className="workflow-lead">Organize patient-provided information and turn uncertainty into useful questions.</p><div className="visit-form">{names.map((name) => <label key={name}>{name}<textarea rows={name === "Symptoms" || name === "Questions for clinician" ? 3 : 2} value={fields[name] || ""} onChange={(event) => setFields({ ...fields, [name]: event.target.value })} placeholder={`Add ${name.toLowerCase()}...`} /></label>)}</div><p className="patient-note"><ShieldCheck size={16} /> Patient-provided information — not a diagnosis.</p><button className="forest-button" onClick={onGenerate}>Generate visit summary <ArrowUpRight size={16} /></button></div>; }

function Sources({ sources, onSelect }: { sources: Source[]; onSelect: (value: number) => void }) { return <div className="workflow-view"><p className="eyebrow">KNOWLEDGE BASE</p><h2>Approved sources.</h2><p className="workflow-lead">Trusted local retrieval keeps answers grounded and transparent.</p><div className="source-list">{sources.length ? sources.map((source) => <button key={source.number} onClick={() => onSelect(source.number)}><span>[{source.number}]</span><div><strong>{source.publisher}</strong><b>{source.title}</b><small>{source.reviewed || "Approved source"}</small></div><ChevronRight size={17} /></button>) : <div className="empty-panel"><BookOpen size={23} /><p>Sources will appear here after your first evidence-supported answer.</p></div>}</div></div>; }

function Privacy({ onClose, onClear }: { onClose: () => void; onClear: () => void }) { return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={onClose}><X size={18} /></button><p className="eyebrow">PRIVACY CENTER</p><h2>Private local processing.</h2><p>Your session is designed to stay close to your device.</p><ul><li><Check size={16} /> Local language model</li><li><Check size={16} /> Local speech transcription</li><li><Check size={16} /> Local document processing</li><li><Check size={16} /> Trusted local retrieval</li><li><Check size={16} /> Chat persistence disabled</li><li><Check size={16} /> Temporary audio cleanup</li></ul><div className="drawer-warning"><strong>Public demo mode</strong><span>Do not enter identifying health information.</span></div><button className="drawer-action" onClick={onClear}><Trash2 size={16} /> Clear session</button><button className="drawer-action secondary"><RefreshCw size={16} /> Clear temporary files</button></aside></div>; }

function Health({ health, onClose, onRetry }: { health: HealthResponse | null; onClose: () => void; onRetry: () => void }) { return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer health-drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={onClose}><X size={18} /></button><p className="eyebrow">SYSTEM STATUS</p><h2>{health?.status === "ok" ? "All systems ready." : "Some services need attention."}</h2><p>{health ? `${health.ready} of ${health.total} services ready.` : "Checking the local AI service..."}</p><div className="health-list">{Object.entries(health?.statuses || {}).map(([key, value]) => <div key={key}><span className={value.status === "ready" ? "status-dot" : "status-dot off"} /><strong>{healthLabels[key] || key}</strong><small>{value.detail}</small></div>)}</div><button className="drawer-action" onClick={onRetry}><RefreshCw size={16} /> Check again</button></aside></div>; }
