"use client";
/* eslint-disable @next/next/no-img-element */

import { ArrowUpRight, BookOpen, Check, FileText, LockKeyhole, Mic, ShieldCheck, Sparkles, Stethoscope, Volume2 } from "lucide-react";

export function PremiumLanding({ onStart }: { onStart: () => void }) {
  return <main className="landing premium-landing">
    <header className="landing-header"><button className="app-brand" onClick={onStart}><span className="brand-mark"><ShieldCheck size={15} /></span><span>MediGuide <em>AI</em></span></button><button className="quiet-button" onClick={onStart}>Open workspace <ArrowUpRight size={15} /></button></header>
    <section className="premium-hero"><div className="premium-hero-copy"><p className="eyebrow"><span /> PRIVATE • LOCAL • EVIDENCE-SUPPORTED</p><h1>Feel more informed.<br /><i>Ask better questions.</i></h1><p>MediGuide helps you understand health information, review documents, use your voice, and prepare for appointments with trusted educational evidence.</p><div className="hero-actions"><button className="forest-button" onClick={onStart}>Start a private session <ArrowUpRight size={17} /></button><button className="quiet-button" onClick={() => document.getElementById("how-medi-guide-works")?.scrollIntoView({ behavior: "smooth" })}>See how MediGuide works <ArrowUpRight size={15} /></button></div><div className="hero-trust"><span><Check size={14} /> Private</span><span><Check size={14} /> Local processing</span><span><Check size={14} /> Cited answers</span></div></div><div className="hero-product-stage"><img src="/assets/mediguide_product_hero.png" alt="MediGuide lab report explanation with evidence and private voice playback" /><div className="hero-badge verified"><FileText size={17} /><span><strong>Document verified</strong><small>Lab report text reviewed</small></span><Check size={16} /></div><div className="hero-badge private"><LockKeyhole size={17} /><span><strong>Processed privately</strong><small>Temporary files cleared</small></span><span className="status-dot" /></div></div></section>
    <section className="feature-proof-strip"><span><FileText size={17} /> Upload documents</span><span><Sparkles size={17} /> Plain-language explanations</span><span><BookOpen size={17} /> Evidence beside every answer</span><span><Volume2 size={17} /> Listen when it helps</span></section>
    <section className="lifestyle-section" id="how-medi-guide-works"><div className="lifestyle-image"><img src="/assets/mediguide_lifestyle.png" alt="Person reviewing a health document at home beside a laptop" /></div><div className="lifestyle-copy"><p className="eyebrow">PREPARE WITH CONTEXT</p><h2>Prepare for more confident <i>health conversations.</i></h2><p>Between appointments, the details can feel scattered. MediGuide gives you a calm place to review what you know, see what is uncertain, and shape useful questions for a professional.</p><div className="visit-preview"><div><Stethoscope size={19} /><span><strong>Visit preparation</strong><small>Symptoms, timeline, questions</small></span></div><div className="visit-progress"><span>Preparation progress</span><b>80%</b><i /></div><button onClick={onStart}>Open visit preparation <ArrowUpRight size={14} /></button></div></div></section>
    <section className="workflow-section document-proof"><div className="workflow-copy"><p className="eyebrow">DOCUMENT WORKFLOW</p><h2>Understand documents without losing <i>context.</i></h2><p>Move from upload to verification to a grounded explanation. The review step keeps names, values, units, and dates in your hands.</p><div className="workflow-steps"><span><b>01</b><strong>Upload</strong><small>Lab_Report.pdf</small></span><span><b>02</b><strong>Verify</strong><small>Clearly visible · Needs review</small></span><span><b>03</b><strong>Understand</strong><small>Plain language + citations</small></span></div></div><div className="workflow-image"><img src="/assets/mediguide_docs_section.png" alt="MediGuide document upload, verification, and explanation workflow" /></div></section>
    <section className="workflow-section voice-proof"><div className="workflow-image"><img src="/assets/mediguide_voice_section.png" alt="MediGuide voice transcript review with highlighted medical details" /></div><div className="workflow-copy"><p className="eyebrow">VOICE, WITH A REVIEW STEP</p><h2>Speak naturally. <i>Review before sending.</i></h2><p>Your voice becomes an editable transcript. MediGuide highlights medication names, numbers, units, and dates before anything is sent to the assistant.</p><div className="voice-callout"><Mic size={18} /><span><strong>Transcript confirmation</strong><small>I reviewed this transcript before sending.</small></span></div></div></section>
    <section className="evidence-section"><div className="evidence-copy"><p className="eyebrow">TRANSPARENT BY DESIGN</p><h2>See where every answer <i>comes from.</i></h2><p>Evidence is not hidden behind a technical layer. It sits beside the explanation, with source names, topics, review dates, and the passages that support the answer.</p><div className="source-mini-list"><span><b>[1]</b><strong>MedlinePlus</strong><small>Hemoglobin information · Reviewed</small></span><span><b>[2]</b><strong>CDC</strong><small>Blood health education · Reviewed</small></span><span><b>[3]</b><strong>FDA</strong><small>Consumer health information · Reviewed</small></span></div></div><div className="evidence-image"><img src="/assets/mediguide_evidence_section.png" alt="MediGuide evidence source cards with citation numbers" /></div></section>
    <footer className="landing-footer"><span><ShieldCheck size={14} /> Educational support, never a diagnosis.</span><span>© 2026 MediGuide AI</span></footer>
  </main>;
}
